# File: tox.ini (Templated version)

#
##
[local_settings]
# project specific local settings
test_pattern = "*Tests.py"
#
# Source paths (unquoted and space separated list of files/directories) for linting and format checks
source_paths = wwpdb/utils/nmr wwpdb/utils/tests-nmr wwpdb/utils/tests-nmr-tox setup.py
#
# Start directory path for test discovery
# Each path must reference valid directory that is searchable by python3.9 (i.e. contains __init__.py)
# It is harmless to point to paths containing no tests.
#
test_path_1 = "wwpdb/utils/tests-nmr-tox"
test_path_2 = "wwpdb/utils/nmr"
#
# Comma separate list of directories/patterns for which test coverage will be evaluated
coverage_source_paths = "wwpdb/utils/nmr,wwpdb/utils/tests-nmr-tox"
coverage_exclude_paths = "wwpdb/__init__.py,wwpdb/utils/tests-nmr/test-output/*"
coverage_cutoff = 17

[flake8]
exclude = wwpdb/utils/tests-nmr/test-output,wwpdb/utils/nmr/obsolete,wwpdb/utils/tests-nmr/obsolete,wwpdb/utils/nmr/mr/AmberMRParser.py,wwpdb/utils/nmr/mr/BareMRParser.py,wwpdb/utils/nmr/mr/CharmmCRDParser.py,wwpdb/utils/nmr/mr/CyanaMRParser.py,,wwpdb/utils/nmr/mr/GromacsMRParser.py,wwpdb/utils/nmr/mr/RosettaMRParser.py,wwpdb/utils/nmr/mr/XplorMRParser.py,wwpdb/utils/nmr/mr/AmberPTParser.py,wwpdb/utils/nmr/mr/BarePDBParser.py,wwpdb/utils/nmr/mr/CharmmMRParser.py,wwpdb/utils/nmr/mr/CyanaNOAParser.py,wwpdb/utils/nmr/mr/GromacsPTParser.py,wwpdb/utils/nmr/mr/SchrodingerMRParser.py,wwpdb/utils/nmr/mr/AriaMRParser.py,wwpdb/utils/nmr/mr/BiosymMRParser.py,wwpdb/utils/nmr/mr/CnsMRParser.py,wwpdb/utils/nmr/mr/DynamoMRParser.py,wwpdb/utils/nmr/mr/IsdMRParser.py,wwpdb/utils/nmr/mr/SybylMRParser.py,wwpdb/utils/nmr/mr/AmberMRLexer.py,wwpdb/utils/nmr/mr/BareMRLexer.py,wwpdb/utils/nmr/mr/CharmmCRDLexer.py,wwpdb/utils/nmr/mr/CyanaMRLexer.py,wwpdb/utils/nmr/mr/GromacsMRLexer.py,wwpdb/utils/nmr/mr/RosettaMRLexer.py,wwpdb/utils/nmr/mr/XplorMRLexer.py,wwpdb/utils/nmr/mr/AmberPTLexer.py,wwpdb/utils/nmr/mr/BarePDBLexer.py,wwpdb/utils/nmr/mr/CharmmMRLexer.py,wwpdb/utils/nmr/mr/CyanaNOALexer.py,wwpdb/utils/nmr/mr/GromacsPTLexer.py,wwpdb/utils/nmr/mr/SchrodingerMRLexer.py,wwpdb/utils/nmr/mr/AriaMRLexer.py,wwpdb/utils/nmr/mr/BiosymMRLexer.py,wwpdb/utils/nmr/mr/CnsMRLexer.py,wwpdb/utils/nmr/mr/DynamoMRLexer.py,wwpdb/utils/nmr/mr/IsdMRLexer.py,wwpdb/utils/nmr/mr/SybylMRLexer.py,wwpdb/utils/nmr/pk/BarePKParser.py,wwpdb/utils/nmr/pk/NmrPipePKParser.py,wwpdb/utils/nmr/pk/NmrViewPKParser.py,wwpdb/utils/nmr/pk/PonderosaPKParser.py,wwpdb/utils/nmr/pk/SparkyPKParser.py,wwpdb/utils/nmr/pk/SparkySPKParser.py,wwpdb/utils/nmr/pk/XeasyPKParser.py,wwpdb/utils/nmr/pk/XMLParser.py,wwpdb/utils/nmr/pk/CcpnPKParser.py,wwpdb/utils/nmr/pk/NmrViewNPKParser.py,wwpdb/utils/nmr/pk/OliviaPKParser.py,wwpdb/utils/nmr/pk/SparkyNPKParser.py,wwpdb/utils/nmr/pk/SparkyRPKParser.py,wwpdb/utils/nmr/pk/VnmrPKParser.py,wwpdb/utils/nmr/pk/XeasyPROTParser.py,wwpdb/utils/nmr/pk/XwinNmrPKParser.py,wwpdb/utils/nmr/pk/BarePKLexer.py,wwpdb/utils/nmr/pk/NmrPipePKLexer.py,wwpdb/utils/nmr/pk/OliviaPKLexer.py,wwpdb/utils/nmr/pk/SparkyPKLexer.py,wwpdb/utils/nmr/pk/VnmrPKLexer.py,wwpdb/utils/nmr/pk/XeasyPROTLexer.py,wwpdb/utils/nmr/pk/XwinNmrPKLexer.py,wwpdb/utils/nmr/pk/CcpnPKLexer.py,wwpdb/utils/nmr/pk/NmrViewPKLexer.py,wwpdb/utils/nmr/pk/PonderosaPKLexer.py,wwpdb/utils/nmr/pk/SparkySPKLexer.py,wwpdb/utils/nmr/pk/XeasyPKLexer.py,wwpdb/utils/nmr/pk/XMLLexer.py,wwpdb/utils/nmr/cs/BareCSParser.py,wwpdb/utils/nmr/cs/GarretCSParser.py,wwpdb/utils/nmr/cs/NmrPipeCSParser.py,wwpdb/utils/nmr/cs/NmrStar2CSParser.py,wwpdb/utils/nmr/cs/OliviaCSParser.py,wwpdb/utils/nmr/cs/PippCSParser.py,wwpdb/utils/nmr/cs/PpmCSParser.py,wwpdb/utils/nmr/cs/BareCSLexer.py,wwpdb/utils/nmr/cs/GarretCSLexer.py,wwpdb/utils/nmr/cs/NmrPipeCSLexer.py,wwpdb/utils/nmr/cs/NmrStar2CSLexer.py,wwpdb/utils/nmr/cs/OliviaCSLexer.py,wwpdb/utils/nmr/cs/PippCSLexer.py,wwpdb/utils/nmr/cs/PpmCSLexer.py

per-file-ignores =
    wwpdb/utils/tests-nmr-tox/*: I100, I101, I200, I201
    wwpdb/utils/tests-nmr/*:     I100, I101, I200, I201

[pylint]
ignore = wwpdb/utils/tests-nmr/test-output,wwpdb/utils/nmr/obsolete,wwpdb/utils/tests-nmr/obsolete,wwpdb/utils/nmr/mr/AmberMRParser.py,wwpdb/utils/nmr/mr/BareMRParser.py,wwpdb/utils/nmr/mr/CharmmCRDParser.py,wwpdb/utils/nmr/mr/CyanaMRParser.py,,wwpdb/utils/nmr/mr/GromacsMRParser.py,wwpdb/utils/nmr/mr/RosettaMRParser.py,wwpdb/utils/nmr/mr/XplorMRParser.py,wwpdb/utils/nmr/mr/AmberPTParser.py,wwpdb/utils/nmr/mr/BarePDBParser.py,wwpdb/utils/nmr/mr/CharmmMRParser.py,wwpdb/utils/nmr/mr/CyanaNOAParser.py,wwpdb/utils/nmr/mr/GromacsPTParser.py,wwpdb/utils/nmr/mr/SchrodingerMRParser.py,wwpdb/utils/nmr/mr/AriaMRParser.py,wwpdb/utils/nmr/mr/BiosymMRParser.py,wwpdb/utils/nmr/mr/CnsMRParser.py,wwpdb/utils/nmr/mr/DynamoMRParser.py,wwpdb/utils/nmr/mr/IsdMRParser.py,wwpdb/utils/nmr/mr/SybylMRParser.py,wwpdb/utils/nmr/mr/AmberMRLexer.py,wwpdb/utils/nmr/mr/BareMRLexer.py,wwpdb/utils/nmr/mr/CharmmCRDLexer.py,wwpdb/utils/nmr/mr/CyanaMRLexer.py,wwpdb/utils/nmr/mr/GromacsMRLexer.py,wwpdb/utils/nmr/mr/RosettaMRLexer.py,wwpdb/utils/nmr/mr/XplorMRLexer.py,wwpdb/utils/nmr/mr/AmberPTLexer.py,wwpdb/utils/nmr/mr/BarePDBLexer.py,wwpdb/utils/nmr/mr/CharmmMRLexer.py,wwpdb/utils/nmr/mr/CyanaNOALexer.py,wwpdb/utils/nmr/mr/GromacsPTLexer.py,wwpdb/utils/nmr/mr/SchrodingerMRLexer.py,wwpdb/utils/nmr/mr/AriaMRLexer.py,wwpdb/utils/nmr/mr/BiosymMRLexer.py,wwpdb/utils/nmr/mr/CnsMRLexer.py,wwpdb/utils/nmr/mr/DynamoMRLexer.py,wwpdb/utils/nmr/mr/IsdMRLexer.py,wwpdb/utils/nmr/mr/SybylMRLexer.py,wwpdb/utils/nmr/pk/BarePKParser.py,wwpdb/utils/nmr/pk/NmrPipePKParser.py,wwpdb/utils/nmr/pk/NmrViewPKParser.py,wwpdb/utils/nmr/pk/PonderosaPKParser.py,wwpdb/utils/nmr/pk/SparkyPKParser.py,wwpdb/utils/nmr/pk/SparkySPKParser.py,wwpdb/utils/nmr/pk/XeasyPKParser.py,wwpdb/utils/nmr/pk/XMLParser.py,wwpdb/utils/nmr/pk/CcpnPKParser.py,wwpdb/utils/nmr/pk/NmrViewNPKParser.py,wwpdb/utils/nmr/pk/OliviaPKParser.py,wwpdb/utils/nmr/pk/SparkyNPKParser.py,wwpdb/utils/nmr/pk/SparkyRPKParser.py,wwpdb/utils/nmr/pk/VnmrPKParser.py,wwpdb/utils/nmr/pk/XeasyPROTParser.py,wwpdb/utils/nmr/pk/XwinNmrPKParser.py,wwpdb/utils/nmr/pk/BarePKLexer.py,wwpdb/utils/nmr/pk/NmrPipePKLexer.py,wwpdb/utils/nmr/pk/OliviaPKLexer.py,wwpdb/utils/nmr/pk/SparkyPKLexer.py,wwpdb/utils/nmr/pk/VnmrPKLexer.py,wwpdb/utils/nmr/pk/XeasyPROTLexer.py,wwpdb/utils/nmr/pk/XwinNmrPKLexer.py,wwpdb/utils/nmr/pk/CcpnPKLexer.py,wwpdb/utils/nmr/pk/NmrViewPKLexer.py,wwpdb/utils/nmr/pk/PonderosaPKLexer.py,wwpdb/utils/nmr/pk/SparkySPKLexer.py,wwpdb/utils/nmr/pk/XeasyPKLexer.py,wwpdb/utils/nmr/pk/XMLLexer.py,wwpdb/utils/nmr/cs/BareCSParser.py,wwpdb/utils/nmr/cs/GarretCSParser.py,wwpdb/utils/nmr/cs/NmrPipeCSParser.py,wwpdb/utils/nmr/cs/NmrStar2CSParser.py,wwpdb/utils/nmr/cs/OliviaCSParser.py,wwpdb/utils/nmr/cs/PippCSParser.py,wwpdb/utils/nmr/cs/PpmCSParser.py,wwpdb/utils/nmr/cs/BareCSLexer.py,wwpdb/utils/nmr/cs/GarretCSLexer.py,wwpdb/utils/nmr/cs/NmrPipeCSLexer.py,wwpdb/utils/nmr/cs/NmrStar2CSLexer.py,wwpdb/utils/nmr/cs/OliviaCSLexer.py,wwpdb/utils/nmr/cs/PippCSLexer.py,wwpdb/utils/nmr/cs/PpmCSLexer.py

## --------------------------------------------------------------------------
## ---------- No project specific setting beyond this point --------------
# Updated:  3-Jul-2019 jdw Cleanup
#           8-Jul-2019 jdw Disable flake8 plugin (pydocstyle compat issue)
#          12-Jul-2019 jdw Add placeholders for up to four test paths
#          13-Jul-2019 jdw Add coverage exclusion
#          21-Nov-2019 jdw py27->py38 update black version
##
[tox]
# The complete list of supported test environments to setup and invoke
# This module requires python 3
envlist = format_pep8-{py39}, lint_pylint-{py39}, format_black-{py39}, py39, test_coverage-{py39}
#
minversion = 3.4.0
skip_missing_interpreters = true
skipsdist = false

[testenv]
passenv = CONFIG_SUPPORT_TOKEN_ENV
allowlist_externals = echo
commands =
    echo "Starting default tests in testenv"

[testenv:py3{9,10,11,12}]
description = 'Run unit tests (unittest runner) using {envpython}'
platform=
    macos: darwin
    linux: linux
skip_install = false
recreate = true
usedevelop=true
deps = -r requirements.txt
commands =
    echo "Starting {envname}"
    {envpython} -V
    {envpython} -m unittest discover -v --start-directory {[local_settings]test_path_1} --pattern "{[local_settings]test_pattern}"
    {envpython} -m unittest discover -v --start-directory {[local_settings]test_path_2} --pattern "{[local_settings]test_pattern}"
    echo "Completed {envname}"

#
[testenv:format_pep8-py3{9,10,11,12}]
description = 'Run selected PEP8 compliance checks (flake8)'
platform=
    macos: darwin
    linux: linux
deps =
    flake8
    # This plugin is no longer compatible with latest pydocstyles -
    # flake8-docstrings>=0.2.7
    flake8-import-order>=0.9
    -r requirements.txt
commands =
    flake8 --max-line-length=132 {[local_settings]source_paths}

#
[testenv:lint_pylint-py3{9,10,11,12}]
description = 'Run linting compliance checks (pylint)'
platform=
     macos: darwin
     linux: linux

deps =
    pylint
    -r requirements.txt
commands =
    echo "Starting {envname}"
    pylint --disable=R,C --reports=n --rcfile={toxinidir}/pylintrc {[local_settings]source_paths}
    echo "Completed {envname}"

#
[testenv:format_black-py3{9,10,11,12}]
description = 'Run format compliance checks (black)'
platform=
    macos: darwin
    linux: linux
deps =
    black>=19.10b0
    -r requirements.txt
    #    isort>=4.3.20
commands =
    echo "Starting {envname}"
    black --check --line-length 132 {[local_settings]source_paths}
    #    isort -rc rcsb/utils --check-only
    echo "Completed {envname}"

#
[testenv:test_coverage-py3{9,10,11,12}]
description = 'Run test coverage analysis'
platform=
    macos: darwin
    linux: linux
recreate = true
usedevelop=true
deps =
    coverage
    -r requirements.txt

commands =
    echo "Starting {envname}"
    coverage erase
    coverage run --parallel-mode --omit="{[local_settings]coverage_exclude_paths}" --source="{[local_settings]coverage_source_paths}" -m unittest discover -v --start-directory {[local_settings]test_path_1} --pattern "{[local_settings]test_pattern}"
    coverage run --parallel-mode --omit="{[local_settings]coverage_exclude_paths}" --source="{[local_settings]coverage_source_paths}" -m unittest discover -v --start-directory {[local_settings]test_path_2} --pattern "{[local_settings]test_pattern}"
    echo " ------- Consolidating {envname} data ----------"
    coverage combine
    echo " ------- Building {envname} reports ----------"
    coverage report --fail-under={[local_settings]coverage_cutoff}
    - coverage xml
    echo "Completed {envname}"
